#!/usr/bin/env bash

# ============================================================================
# Build Translations
# ============================================================================
# This script generates translations.js from JSON translation files
#
# Usage: bash scripts/build-translations.sh
# ============================================================================

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Determine project root (parent of scripts directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

TRANSLATIONS_DIR="$PROJECT_ROOT/translations"
GENERATED_DIR="$PROJECT_ROOT/templates/generated"

echo -e "${BLUE}🌍 Building Translations...${NC}\n"
echo "📂 Project root: $PROJECT_ROOT"
echo ""

# ============================================================================
# Generate translations.js from JSON files
# ============================================================================
echo -e "${GREEN}🔤 Generating translations.js from JSON files...${NC}"

# Start building the JavaScript object
TRANSLATIONS_JS="const TRANSLATIONS = {"

first_lang=true

# Process each JSON file in translations directory
for json_file in "$TRANSLATIONS_DIR"/*.json; do
    [ -f "$json_file" ] || continue
    
    # Get language code from filename (e.g., de.json -> de)
    lang_code=$(basename "$json_file" .json)
    
    echo "  - Processing $lang_code.json"
    
    # Add comma separator for subsequent languages
    if [ "$first_lang" = true ]; then
        first_lang=false
    else
        TRANSLATIONS_JS="$TRANSLATIONS_JS,"
    fi
    
    # Add language code and JSON content
    TRANSLATIONS_JS="$TRANSLATIONS_JS\"$lang_code\": $(cat "$json_file")"
done

TRANSLATIONS_JS="$TRANSLATIONS_JS};"

# Write the generated file (we need to format the JSON properly)
# Build a proper JSON object first, then convert to JS
TRANSLATIONS_JSON="{"
first_json=true

for json_file in "$TRANSLATIONS_DIR"/*.json; do
    [ -f "$json_file" ] || continue
    lang_code=$(basename "$json_file" .json)
    
    if [ "$first_json" = true ]; then
        first_json=false
    else
        TRANSLATIONS_JSON="$TRANSLATIONS_JSON,"
    fi
    
    TRANSLATIONS_JSON="$TRANSLATIONS_JSON\"$lang_code\": $(cat "$json_file")"
done

TRANSLATIONS_JSON="$TRANSLATIONS_JSON}"

# Format and write the file
cat > "$GENERATED_DIR/translations.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: translations/*.json
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-translations.sh
// To modify translations, edit the JSON files in translations/
// and run: bash scripts/build-translations.sh
// This file is included directly in index.html before app.js

const TRANSLATIONS = $(echo "$TRANSLATIONS_JSON" | jq .);
EOF

echo -e "\n${GREEN}✅ Generated: templates/generated/translations.js${NC}\n"

# ============================================================================
# Validation
# ============================================================================
echo -e "${GREEN}🔍 Validating translations...${NC}"

# Get list of all language codes
languages=()
for json_file in "$TRANSLATIONS_DIR"/*.json; do
    [ -f "$json_file" ] || continue
    lang_code=$(basename "$json_file" .json)
    languages+=("$lang_code")
done

echo "  Languages found: ${languages[*]}"

# Get all keys from the first language (reference)
reference_lang="${languages[0]}"
reference_keys=$(jq -r 'keys[]' "$TRANSLATIONS_DIR/$reference_lang.json" | sort)
reference_count=$(echo "$reference_keys" | wc -l | tr -d ' ')

echo "  Reference language: $reference_lang ($reference_count keys)"

# Check each language for missing or extra keys
all_valid=true

for lang in "${languages[@]}"; do
    if [ "$lang" = "$reference_lang" ]; then
        continue
    fi
    
    lang_keys=$(jq -r 'keys[]' "$TRANSLATIONS_DIR/$lang.json" | sort)
    lang_count=$(echo "$lang_keys" | wc -l | tr -d ' ')
    
    # Find missing keys
    missing=$(comm -23 <(echo "$reference_keys") <(echo "$lang_keys"))
    
    # Find extra keys
    extra=$(comm -13 <(echo "$reference_keys") <(echo "$lang_keys"))
    
    if [ -n "$missing" ]; then
        echo "  ⚠️  $lang.json is missing keys:"
        echo "$missing" | sed 's/^/      - /'
        all_valid=false
    fi
    
    if [ -n "$extra" ]; then
        echo "  ⚠️  $lang.json has extra keys:"
        echo "$extra" | sed 's/^/      - /'
        all_valid=false
    fi
    
    if [ -z "$missing" ] && [ -z "$extra" ]; then
        echo "  ✓ $lang.json ($lang_count keys) - complete"
    fi
done

echo ""

if [ "$all_valid" = true ]; then
    echo -e "${GREEN}✨ All translations are valid!${NC}\n"
else
    echo -e "${BLUE}💡 Fix missing/extra keys in translation files${NC}\n"
fi

# ============================================================================
# Summary
# ============================================================================
echo -e "${GREEN}🎉 Build completed successfully!${NC}\n"

echo "📊 Generated files:"
ls -lh "$GENERATED_DIR/translations.js" | awk '{printf "   %s (%s)\n", $9, $5}'

echo ""
echo "💡 Don't forget to commit the updated files:"
echo "   git add translations/*.json templates/generated/translations.js"
echo "   git commit -m 'Update translations'"
