#!/bin/sh
# ============================================================================
# Build Security Levels Template
# Generates templates/generated/security-levels.js from JSON source
# ============================================================================

set -e

# Determine the project root (script is in scripts/ directory)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# File paths
SOURCE_FILE="$PROJECT_ROOT/templates/source/security-levels.json"
OUTPUT_FILE="$PROJECT_ROOT/templates/generated/security-levels.js"

echo "🔨 Building Security Levels Template..."

# Check if source file exists
if [ ! -f "$SOURCE_FILE" ]; then
    echo "❌ Error: Source file not found: $SOURCE_FILE"
    exit 1
fi

# Validate JSON
if ! jq empty "$SOURCE_FILE" 2>/dev/null; then
    echo "❌ Error: Invalid JSON in $SOURCE_FILE"
    exit 1
fi

# Generate timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate the JavaScript file
cat > "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Security Levels - Auto-generated from templates/source/security-levels.json
// Generated: TIMESTAMP_PLACEHOLDER
// DO NOT EDIT THIS FILE DIRECTLY - Edit the source JSON and rebuild
// ============================================================================

EOF

# Add the constant with JSON data
echo "const SECURITY_LEVELS = " >> "$OUTPUT_FILE"
cat "$SOURCE_FILE" >> "$OUTPUT_FILE"
echo ";" >> "$OUTPUT_FILE"

# Replace timestamp placeholder
if command -v gsed > /dev/null 2>&1; then
    gsed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" "$OUTPUT_FILE"
else
    sed -i.bak "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" "$OUTPUT_FILE" && rm -f "$OUTPUT_FILE.bak"
fi

echo "✅ Generated: $OUTPUT_FILE"
echo ""

# Validate generated JavaScript (basic check)
if [ ! -s "$OUTPUT_FILE" ]; then
    echo "❌ Error: Generated file is empty"
    exit 1
fi

echo "✨ Build completed successfully!"
