#!/bin/bash
# Build Script for SEB Config Generator Templates
# 
# This script generates JavaScript module files from JSON source templates.
# Uses jq for JSON processing (install with: brew install jq)

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check for jq
if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠️  jq is not installed. Install with: brew install jq${NC}"
    exit 1
fi

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SOURCE_DIR="$ROOT_DIR/templates/source"
GENERATED_DIR="$ROOT_DIR/templates/generated"

# Ensure generated directory exists
mkdir -p "$GENERATED_DIR"

echo -e "${BLUE}🔨 Building SEB Config Generator Templates...${NC}\n"

# ============================================================================
# Generate presets.js (from services and tools)
# ============================================================================
echo -e "${GREEN}📦 Loading service presets:${NC}"

PRESETS_JSON="{"
first=true

# Load services
for file in "$SOURCE_DIR/services"/*.json; do
    [ -f "$file" ] || continue
    
    id=$(jq -r '.id' "$file")
    name=$(jq -r '.name' "$file")
    
    # Extract config without metadata
    config=$(jq 'del(.name, .description, .category, .language)' "$file")
    
    if [ "$first" = true ]; then
        PRESETS_JSON="$PRESETS_JSON\"$id\": $config"
        first=false
    else
        PRESETS_JSON="$PRESETS_JSON,\"$id\": $config"
    fi
    
    printf "  ✓ %-15s - %s\n" "$id" "$name"
done

echo ""
echo -e "${GREEN}🛠️  Loading reference tools:${NC}"

# Load tools
for file in "$SOURCE_DIR/reference-tools"/*.json; do
    [ -f "$file" ] || continue
    
    id=$(jq -r '.id' "$file")
    name=$(jq -r '.name' "$file")
    
    # Extract config without metadata
    config=$(jq 'del(.name, .description, .category, .language)' "$file")
    
    if [ "$first" = true ]; then
        PRESETS_JSON="$PRESETS_JSON\"$id\": $config"
        first=false
    else
        PRESETS_JSON="$PRESETS_JSON,\"$id\": $config"
    fi
    
    printf "  ✓ %-15s - %s\n" "$id" "$name"
done

PRESETS_JSON="$PRESETS_JSON}"

# Generate presets.js (no export for direct script inclusion)
cat > "$GENERATED_DIR/presets.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: templates/source/services/*.json
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-service-presets.sh
// To modify presets, edit the JSON files in templates/source/services/
// and run: bash scripts/build-service-presets.sh
//
// This file is included directly in index.html before app.js
// Do not use export/import - this is plain JavaScript for direct inclusion

const PRESETS = $(echo "$PRESETS_JSON" | jq .);
EOF

echo -e "\n${GREEN}✅ Generated: templates/generated/presets.js${NC}\n"

# ============================================================================
# Generate preset-groups.js
# ============================================================================
echo -e "${GREEN}📋 Generating preset groups:${NC}"

NO_LOGIN="["
WITH_LOGIN="["
ALL_TOOLS="["

no_login_first=true
with_login_first=true
all_tools_first=true

# Process services
for file in "$SOURCE_DIR/services"/*.json; do
    [ -f "$file" ] || continue
    
    id=$(jq -r '.id' "$file")
    category=$(jq -r '.category' "$file")
    
    if [ "$category" = "noLogin" ]; then
        if [ "$no_login_first" = true ]; then
            NO_LOGIN="$NO_LOGIN\"$id\""
            no_login_first=false
        else
            NO_LOGIN="$NO_LOGIN,\"$id\""
        fi
    elif [ "$category" = "withLogin" ]; then
        if [ "$with_login_first" = true ]; then
            WITH_LOGIN="$WITH_LOGIN\"$id\""
            with_login_first=false
        else
            WITH_LOGIN="$WITH_LOGIN,\"$id\""
        fi
    fi
done

# Process tools (all tools go into ALL_TOOLS array)
# Build array of tool objects with id and name for sorting
tool_array=()
for file in "$SOURCE_DIR/reference-tools"/*.json; do
    [ -f "$file" ] || continue
    
    id=$(jq -r '.id' "$file")
    name=$(jq -r '.name' "$file")
    
    tool_array+=("$name|$id")
done

# Sort tools alphabetically by name, then extract IDs
IFS=$'\n' sorted_tools=($(sort <<<"${tool_array[*]}"))
unset IFS

for tool in "${sorted_tools[@]}"; do
    # Extract ID from "name|id" format
    id="${tool#*|}"
    
    if [ "$all_tools_first" = true ]; then
        ALL_TOOLS="$ALL_TOOLS\"$id\""
        all_tools_first=false
    else
        ALL_TOOLS="$ALL_TOOLS,\"$id\""
    fi
done

NO_LOGIN="$NO_LOGIN]"
WITH_LOGIN="$WITH_LOGIN]"
ALL_TOOLS="$ALL_TOOLS]"

cat > "$GENERATED_DIR/preset-groups.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: templates/source/services/*.json and reference-tools/*.json
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-service-presets.sh
// This file is included directly in index.html before app.js

const PRESET_GROUPS = {
    "noLogin": $(echo "$NO_LOGIN" | jq .),
    "withLogin": $(echo "$WITH_LOGIN" | jq .),
    "allTools": $(echo "$ALL_TOOLS" | jq .)
};
EOF

echo -e "${GREEN}✅ Generated: templates/generated/preset-groups.js${NC}\n"

# ============================================================================
# Generate subjects.js
# ============================================================================
echo -e "${GREEN}📚 Loading subject configurations:${NC}"

SUBJECTS_JSON="{"
first=true

for file in "$SOURCE_DIR/subjects"/*.json; do
    [ -f "$file" ] || continue
    
    id=$(jq -r '.id' "$file")
    name=$(jq -r '.name' "$file")
    toolPresets=$(jq -r '.toolPresets' "$file")
    
    # Handle wildcard "*" to include all tools
    if [ "$toolPresets" = "*" ]; then
        # Use ALL_TOOLS array generated earlier
        config="{\"toolPresets\": $ALL_TOOLS}"
    else
        config=$(jq '{toolPresets}' "$file")
    fi
    
    if [ "$first" = true ]; then
        SUBJECTS_JSON="$SUBJECTS_JSON\"$id\": $config"
        first=false
    else
        SUBJECTS_JSON="$SUBJECTS_JSON,\"$id\": $config"
    fi
    
    printf "  ✓ %-15s - %s\n" "$id" "$name"
done

SUBJECTS_JSON="$SUBJECTS_JSON}"

cat > "$GENERATED_DIR/subjects.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: templates/source/subjects/*.json
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-service-presets.sh
// To modify subjects, edit the JSON files in templates/source/subjects/
// and run: bash scripts/build-service-presets.sh
// This file is included directly in index.html before app.js

const SUBJECTS = $(echo "$SUBJECTS_JSON" | jq .);
EOF

echo -e "\n${GREEN}✅ Generated: templates/generated/subjects.js${NC}\n"

# ============================================================================
# Generate platform-specific JS files from JSON
# ============================================================================
echo -e "${GREEN}🖥️  Generating platform-specific files:${NC}"

for file in "$SOURCE_DIR/platforms"/*.json; do
    [ -f "$file" ] || continue
    
    basename=$(basename "$file" .json)
    
    # Generate JS file with same structure as original
    cat > "$GENERATED_DIR/${basename}.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: templates/source/platforms/${basename}.json
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-service-presets.sh
// To modify, edit templates/source/platforms/${basename}.json
// and run: bash scripts/build-service-presets.sh

const ${basename//-/_} = $(jq . "$file");
EOF

    printf "  ✓ %s\n" "$basename.js"
done

echo -e "\n${GREEN}✅ Generated platform-specific files${NC}\n"

# ============================================================================
# Generate xml-data.js from example_config.xml
# ============================================================================
if [ -f "$SOURCE_DIR/example_config.xml" ]; then
    echo -e "${GREEN}📄 Generating xml-data.js from example_config.xml:${NC}"
    
    # Read XML and escape it for JavaScript
    xml_content=$(cat "$SOURCE_DIR/example_config.xml" | sed 's/`/\\`/g' | sed 's/\$/\\$/g')
    
    cat > "$GENERATED_DIR/xml-data.js" << EOF
// Generated file - DO NOT EDIT MANUALLY
// Source: templates/source/example_config.xml
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
//
// This file is automatically generated by scripts/build-service-presets.sh
// To modify the template, edit templates/source/example_config.xml
// and run: bash scripts/build-service-presets.sh

const exampleConfigXML = \`${xml_content}\`;
EOF

    echo -e "  ✓ xml-data.js"
    echo -e "\n${GREEN}✅ Generated xml-data.js${NC}\n"
fi

# ============================================================================
# Generate README
# ============================================================================
cat > "$ROOT_DIR/templates/README.md" << 'EOF'
# Service & Subject Templates

This directory contains the template system for SEB Config Generator presets.

## 📁 Directory Structure

```
templates/
├── source/                   # Source JSON/XML files (edit these!)
│   ├── services/             # Service/tool presets
│   │   ├── onenote.json      # OneNote preset
│   │   ├── whiteboard.json   # Whiteboard.fi preset
│   │   ├── duden.json        # Duden dictionary
│   │   └── ...               # More services
│   ├── subjects/             # Subject configurations
│   │   ├── german.json       # German language tools
│   │   ├── english.json      # English language tools
│   │   └── french.json       # French language tools
│   ├── platforms/            # Platform-specific boolean options
│   │   ├── boolean-options-locations-macos.json
│   │   ├── boolean-options-locations-windows.json
│   │   └── boolean-options-locations-ipados.json
│   └── example_config.xml    # SEB config XML template
└── generated/                # Generated JS files (auto-generated)
    ├── presets.js            # All service presets
    ├── subjects.js           # All subject configurations
    ├── preset-groups.js      # Categorized preset groups
    ├── boolean-options-locations-*.js  # Platform option mappings
    └── xml-data.js           # XML template as JS constant
```

## 🎯 How to Add a New Service

### 1. Create a new JSON file in `source/services/`

Example: `templates/source/services/mynewservice.json`

```json
{
  "id": "mynewservice",
  "name": "My New Service",
  "description": "Description for UI",
  "category": "noLogin",
  "startUrl": "https://example.com",
  "domains": [
    "example.com",
    "*.example.com"
  ]
}
```

### 2. Available Categories

- `noLogin` - Services without authentication (e.g., Kahoot, Whiteboard.fi)
- `withLogin` - Services requiring login (e.g., OneNote, Word Online)
- `allowedTools` - Subject-specific tools (dictionaries, calculators)

For `allowedTools`, add `"language": "german"` (or english, french, etc.)

### 3. Run the build script

```bash
bash scripts/build-service-presets.sh
```

### 4. Test your changes

The generated files are automatically imported by `js/app.js`.

## 🌍 How to Add a New Subject

### 1. Create a new JSON file in `source/subjects/`

Example: `templates/source/subjects/spanish.json`

```json
{
  "id": "spanish",
  "name": "Español",
  "toolPresets": ["rae", "wordreference"]
}
```

### 2. Add the corresponding tool services

Create `source/services/rae.json` and `source/services/wordreference.json`

### 3. Run the build script

```bash
bash scripts/build-service-presets.sh
```

## 🔄 When to Rebuild

Run `bash scripts/build-service-presets.sh` whenever you:
- Add a new service JSON file
- Modify an existing service JSON file
- Add a new subject JSON file
- Change subject tool associations

## 🤝 Contributing

1. Fork the repository
2. Add your service/subject JSON files
3. Run the build script
4. Test the changes locally
5. Submit a pull request

**Note:** Only modify files in `source/` directory. Never edit files in `generated/` directly!

## 📝 JSON Schema Reference

### Service Preset Schema

```typescript
{
  id: string;              // Unique identifier (lowercase, no spaces)
  name: string;            // Display name for UI
  description: string;     // Brief description
  category: "noLogin" | "withLogin" | "allowedTools";
  language?: string;       // Required for allowedTools category
  startUrl: string;        // Starting URL
  domains: string[];       // Allowed domains (wildcards supported)
  blockedDomains?: string[]; // Optional: Explicitly blocked domains
}
```

### Subject Schema

```typescript
{
  id: string;              // Unique identifier (lowercase)
  name: string;            // Display name for UI
  toolPresets: string[];   // Array of tool preset IDs
}
```

---

**Script:** `scripts/build-service-presets.sh`
EOF

echo -e "${GREEN}✅ Generated: templates/README.md${NC}\n"

echo -e "${BLUE}✨ Build completed successfully!${NC}\n"
echo -e "${YELLOW}📌 Next steps:${NC}"
echo -e "   1. Review generated files in templates/generated/"
echo -e "   2. Import in js/app.js (if not already done)"
echo -e "   3. Test the application"
echo -e "   4. Commit both source and generated files\n"
